coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 50%

flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 5%
      - type: patch
        target: 50%
  individual_flags:
    - name: unit
      paths:
        - src/
    - name: sway
    - name: i3
    - name: hyprland
    - name: niri
    - name: dwm

ignore:
  - "build.zig"
