coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 50%

flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 5%
      - type: patch
        target: 50%
  individual_flags:
    - name: unit
      paths:
        - src/
    - name: sway
      paths:
        - src/
        - "!src/hooks/"
    - name: i3
      paths:
        - src/
        - "!src/hooks/"
    - name: hyprland
      paths:
        - src/
        - "!src/hooks/"
    - name: niri
      paths:
        - src/
        - "!src/hooks/"
    - name: dwm
      paths:
        - src/
        - "!src/hooks/"
    - name: river
      paths:
        - src/
        - "!src/hooks/"

ignore:
  - "build.zig"
